Node.js module that serves Coveo search tokens for Dynamics portal.
coveo/coveo-search-token-generator pull request #1
Opened 2018-11-15 22:48 UTC by aminduca

Node.js module that serves Coveo search tokens for Dynamics portal.

The sample folder contains an Express server that generates Coveo search tokens for Dynamics portal.

2018-11-15 23:06 UTC, aminduca commented on samples/sample-token-server-azure/Index.ts
> +        const portalAuth: IDecodedPortalAuthTokenPayload = await portal.decodeAuthToken(req.headers.authorization);
Handle anonymous (no auth token).

2018-11-15 23:07 UTC, aminduca commented on lib/src/CoveoSearchTokenHandler.ts
> +        const impersonatedUser: ISearchTokenBodyRequest = {
Handle anonymous (no userEmail)

2018-11-16 18:36 UTC, lbergeron requested changes

2018-11-16 18:36 UTC, lbergeron commented on README.md
> +// Gets a search token from Coveo for the user specified in the token.
I would add an empty line between both snippets.

2018-11-16 18:36 UTC, lbergeron commented on lib/README.md
> +// Gets a search token from Coveo for the user specified in the token.
I would add an empty line between both snippets.

2018-11-16 18:36 UTC, lbergeron commented on lib/package.json
> +        "xrm",
I'm not so sure about the `xrm` keyword.

2018-11-16 18:36 UTC, lbergeron commented on lib/package.json
> +        "build": "npm run setup && npm run ts",
By having `npm run setup` in this script, `npm install` would be executed every time `npm run build` is called.

2018-11-16 18:36 UTC, lbergeron commented on lib/src/AuthTokenDecoder.ts
> +export class AuthTokenDecoder {
Given this library deals with more than one token type, I would rename the class to `PortalTokenDecoder`.

2018-11-16 18:36 UTC, lbergeron commented on lib/src/CoveoSearchTokenHandler.ts
> +     * Gets or create a search token for the given user.
I would use `Get a search token for the given user.` since there is no caching in the library.

2018-11-16 18:36 UTC, lbergeron commented on lib/src/CoveoSearchTokenHandler.ts
> +        const impersonatedUser: ISearchTokenBodyRequest = {
When you want to represent an anonymous user, you can use `anonymous@anonymous` for instance.

2018-11-16 18:36 UTC, lbergeron commented on lib/src/CoveoSearchTokenHandler.ts
> +                    if (res.statusCode < 200 || res.statusCode > 299) {
I think it might be a little more readable by inverting the condition.

    if (res.statusCode >= 200 && res.statusCode < 300) {
        const tokenResponse: ISearchTokenResponse = JSON.parse(data);
        resolve(tokenResponse.token);
    } else {
        reject(res);
    }

2018-11-16 18:36 UTC, lbergeron commented on lib/src/AuthTokenDecoder.ts
> +import * as jwt from "jsonwebtoken";
I guess we should add the Coveo copyright to our source files.

2018-11-16 18:36 UTC, lbergeron commented on lib/src/DynamicsPortalAuthTokenHandler.ts
> +                this._lastPublicKey = publicKey;
I am wondering whether the public key can change over time. It is probably good enough to indicate in the documentation that if the public key changes, the service must be restarted. We should provide a example for the error that is thrown.

2018-11-16 18:36 UTC, lbergeron commented on lib/src/DynamicsPortalAuthTokenHandler.ts
> +                    if (res.statusCode < 200 || res.statusCode > 299) {
I would invert the condition to use `res.statusCode >= 200 && res.statusCode < 300`.

2018-11-16 18:36 UTC, lbergeron commented on samples/sample-token-server-azure/Index.ts
> +const config = {
I would suggest to create a `config.json` file to put this data.

You can then import it with `import * as config from "./config.json";`

2018-11-16 18:36 UTC, lbergeron commented on samples/sample-token-server-azure/Index.ts
> +import * as expServer from "express";
I would use `express` instead of `expServer`, to keep the same variable name as in the [Express examples](https://www.npmjs.com/package/express). It seems a little more standard to me.

2018-11-16 18:36 UTC, lbergeron commented on samples/sample-token-server-azure/Index.ts
> +const port: string | number = process.env.PORT || 5950;
Do you know if there is any special reason to use this port number?

The port number is used at least at two places, I would suggest to use a constant instead.

2018-11-16 18:36 UTC, lbergeron commented on samples/sample-token-server-azure/Index.ts
> +    post("/token", getCoveoToken).
It might be nice to handle `GET /` and return something like `Server is ready` or something like that. It would allow someone to easily see whether the service is up and running. It could be handy to troubleshoot connection and firewall issues.

It could even be used with load-balancer probes to detect whether the service is alive.

2018-11-16 18:36 UTC, lbergeron commented on samples/sample-token-server-azure/README.md
> +Before running the sample, open `Index.ts` and change this configuration accordingly to represent your environment.
Modify the file if the configuration moves to a config file. The snippet would need to be updated too.

2018-11-16 18:36 UTC, lbergeron commented on samples/sample-token-server-azure/package.json
> +        "xrm",
I don't think the `xrm` keyword is relevant here.

2018-11-16 18:47 UTC, lbergeron requested changes

2018-11-16 18:47 UTC, lbergeron commented on lib/package.json
> +        "build": "rm -rf dist && npm run ts",
I would suggest to add a "clean" script.

2018-11-16 18:47 UTC, lbergeron commented on lib/src/CoveoSearchTokenHandler.ts
> +                name: userEmail || "anonymous@coveo.com",
I would suggest to use `anonymous@anonymous` to avoid ending with `anonymous@coveo.com` in the security cache.

2018-11-16 20:57 UTC, lbergeron approved these changes

2018-11-16 22:06 UTC, merged