Refactoring for readability purposes
coveo/coveo-search-token-generator pull request #2
Opened 2018-11-21 17:17 UTC by aminduca

- Removed all azure related content
- Renamed classes
- Added comments

2018-11-21 21:10 UTC, lbergeron requested changes

2018-11-21 21:10 UTC, lbergeron commented on lib/LICENSE
> +Copyright (c) 2018 Coveo
Trust me, you want to keep the original copyright format!

2018-11-21 21:10 UTC, lbergeron commented on lib/README.md
>  // Gets a search token from Coveo for the user specified in the token.
Since the method name is `fetchSearchToken`, I would start the comment with `Fetches ...`.

2018-11-21 21:10 UTC, lbergeron commented on lib/src/CoveoSearchTokenGenerator.ts
>       * Gets or create a search token for the given user.
I would use "Fetches a search token..."

2018-11-21 21:10 UTC, lbergeron commented on samples/node-token-server/Index.ts
>      coveoPlatformUrl: "platform.cloud.coveo.com" // The URL of the Coveo Cloud V2 platform.
Since "Coveo Cloud" is a product name, I would use "The Coveo Cloud URL." instead.

2018-11-21 21:10 UTC, lbergeron commented on samples/node-token-server/LICENSE
> +Copyright (c) 2018 Coveo
You should use this copyright format instead.

`Copyright (c) 2005-2018 Coveo Solutions Inc.`

2018-11-21 21:10 UTC, lbergeron commented on samples/node-token-server/README.md
> +    portalUrl: "<your_portal_url>", // Example: https://yourportalurl.microsoftcrmportals.com (without slash at the end)
I suggest we handle the ending slash in the code. It is pretty annoying when a piece of software breaks because of an assumption like that.

2018-11-21 21:10 UTC, lbergeron commented on samples/node-token-server/package.json
> +        "coveo-search-token-generator": "file:../../lib"
I guess we should not commit this.

2018-11-21 21:27 UTC, aminduca commented on lib/LICENSE
> +Copyright (c) 2018 Coveo
loool 👍

2018-11-22 18:02 UTC, lbergeron approved these changes

2018-11-22 18:19 UTC, merged